CREATE TABLE IF NOT EXISTS INVOICE (
    ID UUID PRIMARY KEY,
    DATE DATE NOT NULL,
    CUSTOMER VARCHAR(120) NOT NULL,
    BASE_CURRENCY CHAR(3) NOT NULL,
    BASE_AMOUNT DECIMAL(19,6) NOT NULL,
    CREATE_AT TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS IDX_INVOICE_DATE ON INVOICE(DATE);
CREATE INDEX IF NOT EXISTS IDX_INVOICE_CUSTOMER ON INVOICE(CUSTOMER);

CREATE TABLE IF NOT EXISTS FX_RATE (
    RATE_DATE DATE NOT NULL,
    BASE CHAR(3) NOT NULL,
    TARGET CHAR(3) NOT NULL,
    RATE DECIMAL(19, 8) NOT NULL,
    SOURCE VARCHAR(40) NOT NULL,
    RETRIEVED_AT TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT PK_FX_RATE PRIMARY KEY (RATE_DATE, BASE, TARGET)
);

CREATE INDEX IF NOT EXISTS IDX_FX_RATE_BASE_TARGET ON FX_RATE(BASE, TARGET)